name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: nix build packages/*.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: basename -s .nix packages/* | sed 's/.*/.#&/' | xargs nix build
  format:
    name: nix fmt -- --check **/*.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix fmt -- --check **/*.nix
  statix:
    name: statix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix run nixpkgs#statix check
  nixd:
    name: nixf-tidy --variable-lookup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix run github:donovanglover/nix-config#nixf-tidy
